# Generated by Django 4.0.5 on 2022-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.SlugField(default='asdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='linux',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
