# Generated by Django 4.0.5 on 2022-07-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='software',
            name='features',
            field=models.ManyToManyField(to='software.feature'),
        ),
    ]
