# Generated by Django 4.0.5 on 2022-07-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_feature_software_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
    ]
