# Generated by Django 4.0.5 on 2022-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_developer_slug_alter_software_linux'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='asdf', max_length=30),
            preserve_default=False,
        ),
    ]
