# Generated by Django 4.0.5 on 2022-07-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_alter_feature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['sequence', 'name']},
        ),
    ]
