# Generated by Django 4.0.5 on 2022-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_alter_feature_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='software.feature'),
        ),
    ]
